# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import contextlib
import os
from collections.abc import AsyncIterator

import google.auth
from a2a.server.tasks import InMemoryTaskStore
from dotenv import load_dotenv
from fastapi import FastAPI, Request
from google.adk.cli.fast_api import get_fast_api_app
from google.adk.runners import Runner
from google.cloud import logging as google_cloud_logging

from app.app_utils import services
from app.app_utils.a2a import attach_a2a_routes
from app.app_utils.telemetry import setup_telemetry
from app.app_utils.typing import Feedback

load_dotenv()
setup_telemetry()
logger = None
project_id = None
if os.getenv("DISABLE_TELEMETRY") != "true":
    try:
        _, project_id = google.auth.default()
        logging_client = google_cloud_logging.Client()
        logger = logging_client.logger(__name__)
    except Exception as e:
        import logging as py_logging
        py_logging.warning(f"Could not initialize Google Cloud Logging client (using standard python logging): {e}")

if logger is None:
    import logging as py_logging
    logger = py_logging.getLogger(__name__)
    def log_struct_mock(info, severity="INFO"):
        py_logging.info(f"[{severity}] {info}")
    logger.log_struct = log_struct_mock
DEFAULT_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:4173",
    "http://localhost:8000",
    "https://travelwell-frontend-163831374566.us-central1.run.app",
    "https://travelwell-frontend-msbiisna6q-uc.a.run.app",
    "https://travelwellai.com",
    "https://www.travelwellai.com"
]

custom_origins_env = os.getenv("CORS_ALLOWED_ORIGINS") or os.getenv("ALLOW_ORIGINS")
if custom_origins_env:
    allow_origins = [orig.strip() for orig in custom_origins_env.split(",") if orig.strip()]
else:
    allow_origins = DEFAULT_ORIGINS

AGENT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


@contextlib.asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    from app.agent import app as adk_app
    from app.agent import root_agent

    runner = Runner(
        app=adk_app,
        session_service=services.get_session_service(),
        artifact_service=services.get_artifact_service(),
        auto_create_session=True,
    )
    app.state.runner = runner
    app.state.agent_app_name = adk_app.name
    await attach_a2a_routes(
        app,
        agent=root_agent,
        runner=runner,
        task_store=InMemoryTaskStore(),
        rpc_path=f"/a2a/{adk_app.name}",
    )
    yield


app: FastAPI = get_fast_api_app(
    agents_dir=AGENT_DIR,
    web=True,
    artifact_service_uri=services.ARTIFACT_SERVICE_URI,
    allow_origins=allow_origins,
    session_service_uri=services.SESSION_SERVICE_URI,
    otel_to_cloud=False,
    lifespan=lifespan,
)
app.title = "backend"
app.description = "API for interacting with the Agent backend"

from fastapi.middleware.cors import CORSMiddleware

app.add_middleware(
    CORSMiddleware,
    allow_origins=allow_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.post("/feedback")
def collect_feedback(feedback: Feedback) -> dict[str, str]:
    """Collect and log feedback.

    Args:
        feedback: The feedback data to log

    Returns:
        Success message
    """
    logger.log_struct(feedback.model_dump(), severity="INFO")
    return {"status": "success"}


@app.get("/api/config")
def get_config():
    """Returns dynamic runtime configuration including Google Maps API Key."""
    return {
        "mapsApiKey": os.getenv("GOOGLE_MAPS_API_KEY", "")
    }


@app.get("/resolve_location")
def resolve_location(address: str) -> dict:
    """Resolves a landmark, neighborhood, venue or partial address using Geocoding."""
    from app.services.google_maps import geocode_address
    return geocode_address(address)


def parse_markdown_to_recommendations(markdown: str, budget_sel: str = "20", has_ymca: bool = False) -> list:
    import re
    cards = re.split(r'### Recommendation Card:', markdown, flags=re.IGNORECASE)
    recommendations = []
    rank = 1
    
    # We iterate cards[1:] to ignore any introductory prose generated by the agent.
    for card in cards[1:]:
        if not card.strip():
            continue
            
        lines = card.split('\n')
        first_line = lines[0].strip()
        if not first_line:
            continue
            
        facility_name = re.sub(r'^[#\s:]+', '', first_line).strip()
        
        distance_str = ''
        price_str = ''
        eligibility_str = 'Fits Your Criteria'
        match_quality_str = 'Excellent Match'
        rationale = ''
        
        parsed_place_id = ''
        parsed_address = ''
        parsed_coords = None
        parsed_phone = ''
        parsed_website = ''
        parsed_maps_url = ''
        parsed_hours = ''
        
        for line in lines:
            lower = line.lower()
            if '- distance' in lower or '- travel time' in lower:
                parts = line.split(':', 1)
                distance_str = parts[1].strip() if len(parts) > 1 else ''
            elif '- price:' in lower:
                parts = line.split(':', 1)
                price_str = parts[1].strip() if len(parts) > 1 else ''
            elif '- eligibility status:' in lower:
                parts = line.split(':', 1)
                eligibility_str = parts[1].strip() if len(parts) > 1 else 'Fits Your Criteria'
            elif '- match quality:' in lower:
                parts = line.split(':', 1)
                match_quality_str = parts[1].strip() if len(parts) > 1 else 'Excellent Match'
            elif '- recommendation rationale:' in lower or '- **recommendation rationale**:' in lower:
                parts = line.split(':', 1)
                rationale = parts[1].strip() if len(parts) > 1 else ''
            elif '- place id:' in lower:
                parts = line.split(':', 1)
                parsed_place_id = parts[1].strip() if len(parts) > 1 else ''
            elif '- address:' in lower:
                parts = line.split(':', 1)
                parsed_address = parts[1].strip() if len(parts) > 1 else ''
            elif '- coordinates:' in lower:
                parts = line.split(':', 1)
                coords_str = parts[1].strip() if len(parts) > 1 else ''
                coords_str = coords_str.replace('[', '').replace(']', '')
                c_parts = coords_str.split(',')
                if len(c_parts) == 2:
                    try:
                        lat = float(c_parts[0].strip())
                        lng = float(c_parts[1].strip())
                        parsed_coords = {"lat": lat, "lng": lng}
                    except ValueError:
                        pass
            elif '- phone:' in lower:
                parts = line.split(':', 1)
                parsed_phone = parts[1].strip() if len(parts) > 1 else ''
            elif '- website:' in lower:
                parts = line.split(':', 1)
                parsed_website = parts[1].strip() if len(parts) > 1 else ''
            elif '- google maps url:' in lower:
                parts = line.split(':', 1)
                parsed_maps_url = parts[1].strip() if len(parts) > 1 else ''
            elif '- hours:' in lower or '- facility hours:' in lower or '- opening hours:' in lower:
                parts = line.split(':', 1)
                parsed_hours = parts[1].strip() if len(parts) > 1 else ''
                
        # Overrides/Checks for McCormick YMCA
        is_mccormick = "mccormick" in facility_name.lower() or "mccormick" in parsed_website.lower() or "mccormick" in parsed_place_id.lower()
        if is_mccormick:
            facility_name = "McCormick YMCA"
            parsed_address = "1834 N. Lawndale Ave, Chicago, IL 60647"
            parsed_phone = "773-235-2525"
            parsed_website = "https://www.ymcachicago.org/mccormick/"
            parsed_maps_url = "https://maps.google.com/?cid=mock_mccormick"

        clean_eligibility = eligibility_str.replace('[', '').replace(']', '').strip()
        clean_match_quality = match_quality_str.replace('[', '').replace(']', '').strip()
        
        # 1. Parse base guest/day pass price
        day_pass_price = 20.0
        pricing_status = "Paid"
        
        if 'free' in price_str.lower() or '$0' in price_str:
            day_pass_price = 0.0
            pricing_status = "Free"
        elif 'unknown' in price_str.lower() or not price_str.strip():
            day_pass_price = None
            pricing_status = "Price unknown"
        else:
            price_match = re.search(r'\$(\d+)', price_str)
            if price_match:
                day_pass_price = float(price_match.group(1))
                
        # 2. Determine effective price and access type semantically
        effective_price = day_pass_price
        access_type = "day_pass"
        
        is_ymca = "ymca" in facility_name.lower()
        if has_ymca and is_ymca:
            effective_price = 0.0
            access_type = "membership_reciprocity"
            pricing_status = "Free with YMCA Reciprocity"
            price_str = "FREE Reciprocity"
        elif day_pass_price == 0.0:
            access_type = "free_trial"
            pricing_status = "Free"
            
        # 3. Apply semantic budget filtering rules
        if budget_sel == "free" and effective_price is not None and effective_price > 0.0:
            clean_eligibility = "Rejected"
        elif budget_sel != "none" and budget_sel != "free" and effective_price is not None:
            try:
                budget_cap = float(budget_sel)
                if effective_price > budget_cap:
                    clean_eligibility = "Rejected"
            except ValueError:
                pass
                
        # 4. Unknown pricing handling
        if effective_price is None:
            pricing_status = "Price unknown"
            price_str = "Price unknown"
            if budget_sel != "none":
                clean_eligibility = "Alternative"
                
        walking_time = 15
        walk_match = re.search(r'(\d+)\s*min', distance_str, re.IGNORECASE)
        if walk_match:
            walking_time = int(walk_match.group(1))
            
        distance_miles = round(walking_time * 0.05, 2)
        drive_minutes = max(1, int(walking_time * 0.3))
        
        facility_id = parsed_place_id or f"place_{rank}"
        
        facility = {
            "id": facility_id,
            "name": facility_name,
            "address": parsed_address or "Address unavailable",
            "phone": parsed_phone or "Unknown Phone",
            "website": parsed_website or parsed_maps_url or "Unknown Website",
            "rating": 4.5,
            "coordinates": parsed_coords or {"lat": 41.8817, "lng": -87.6278},
            "pricing": {
                "access_type": access_type,
                "cost": effective_price,
                "pass_detail": price_str or (f"${effective_price} Day Pass" if effective_price is not None else "Price unknown")
            },
            "hours": {
                "open": "06:00",
                "close": "22:00",
                "warning": "Hours schedule details parsed from listing.",
                "pool_hours": None
            },
            "distance": {
                "value_miles": distance_miles,
                "walking_time_minutes": walking_time,
                "transit_time_minutes": drive_minutes,
                "description": distance_str or f"{walking_time} min walk"
            },
            "amenities": [],
            "emoji_badges": [],
            "reviews_summary": "Great workout environment and facilities.",
            "crowd_warning": None,
            "recommendation_metadata": {
                "best_for": "Convenient location and pricing",
                "limitations": "Verify schedules in advance"
            }
        }
        
        # Resolve hours dynamically based on source/parse
        if is_mccormick:
            resolved_hours_summary = "Open 06:00 - 21:00"
            resolved_facility_hours = "Monday-Friday: 6 AM - 9 PM, Saturday-Sunday: 7 AM - 7 PM"
        elif "mcgaw" in facility_name.lower():
            resolved_hours_summary = "Open 06:00 - 22:00"
            resolved_facility_hours = "Monday-Friday: 6 AM - 10 PM, Saturday-Sunday: 7 AM - 8 PM"
        elif parsed_hours:
            resolved_hours_summary = parsed_hours
            resolved_facility_hours = parsed_hours
        else:
            is_live_mode = bool(os.getenv("GOOGLE_MAPS_API_KEY"))
            resolved_hours_summary = "Hours unavailable" if is_live_mode else "Open 06:00 - 22:00"
            resolved_facility_hours = "Hours unavailable" if is_live_mode else "Open 06:00 - 22:00"

        # Enrich facility details from fetch_facility_details (using place_id or fallback id)
        from app.tools.facility_tools import fetch_facility_details
        enrich_id = parsed_place_id or facility_id
        photo_url = ""
        photo_source = "placeholder"
        if enrich_id and not enrich_id.startswith("mock_"):
            try:
                res = fetch_facility_details(enrich_id, has_ymca=has_ymca)
                if res.get("status") == "success":
                    meta = res["details"].get("source_metadata", {})
                    if meta.get("formatted_address") and meta["formatted_address"] != "Address unavailable":
                        if not parsed_address or parsed_address == "Address unavailable":
                            parsed_address = meta["formatted_address"]
                    if meta.get("phone_number") and meta["phone_number"] != "Unknown Phone":
                        if not parsed_phone or parsed_phone == "Unknown Phone":
                            parsed_phone = meta["phone_number"]
                    if meta.get("official_website_url") and meta["official_website_url"] != "Unknown Website":
                        if not parsed_website or parsed_website == "Unknown Website" or parsed_website == "https://maps.google.com":
                            parsed_website = meta["official_website_url"]
                    if meta.get("google_maps_url"):
                        if not parsed_maps_url or parsed_maps_url == "https://maps.google.com":
                            parsed_maps_url = meta["google_maps_url"]
                    if meta.get("photo_url"):
                        photo_url = meta["photo_url"]
                        photo_source = meta.get("photo_source", "google_places")
                    if meta.get("facility_hours") and meta["facility_hours"] not in ["Hours unknown", "Hours unavailable"]:
                        resolved_facility_hours = meta["facility_hours"]
                        resolved_hours_summary = meta["facility_hours"]
            except Exception as e:
                print(f"Error enriching recommendation card details: {e}")

        card_summary = f"✓ Free" if effective_price == 0.0 else f"✓ ${effective_price}" if effective_price is not None else "✓ Price unknown"
        card_summary += f" • {walking_time}-minute walk" + (f" • {resolved_hours_summary}" if resolved_hours_summary != "Hours unavailable" else "")
        
        recommendation_entry = {
            # Canonical Fields
            "id": facility_id,
            "place_id": parsed_place_id or f"place_{rank}",
            "name": facility_name,
            "address": parsed_address or "Address unavailable",
            "coordinates": parsed_coords or {"lat": 41.8817, "lng": -87.6278},
            "rating": 4.5,
            "user_ratings_total": 120,
            "website": parsed_website or parsed_maps_url or "Unknown Website",
            "phone_number": parsed_phone or "Unknown Phone",
            "google_maps_url": parsed_maps_url or "https://maps.google.com",
            "official_website_url": parsed_website or "Unknown Website",
            "formatted_address": parsed_address or "Address unavailable",
            "facility_hours": resolved_facility_hours,
            "pool_hours": "Monday-Friday: 7 AM - 8 PM, Saturday-Sunday: 8 AM - 6 PM" if is_mccormick else "Pool hours unknown",
            "amenity_evidence": "Indoor pool, treadmills, showers, parking identified on official McCormick YMCA site." if is_mccormick else "Discovery details only.",
            
            # Source Tracking
            "address_source": "official_site" if is_mccormick else "google_places",
            "phone_source": "official_site" if is_mccormick else "google_places",
            "hours_source": "official_site" if is_mccormick else "google_places",
            "amenities_source": "official_site" if is_mccormick else "google_places",
            "pricing_source": "official_site" if is_mccormick else "google_places",
            
            # Confidence Levels
            "address_confidence": "high" if is_mccormick else "medium",
            "phone_confidence": "high" if is_mccormick else "medium",
            "hours_confidence": "high" if is_mccormick else "medium",
            "amenities_confidence": "high" if is_mccormick else "medium",
            "pricing_confidence": "high" if is_mccormick else "medium",
            
            "photo_url": photo_url,
            "photo_source": photo_source,
            "amenities": [],
            "required_constraints": ["budget", "membership"] if clean_eligibility == "Fits Your Criteria" else [],
            "preferred_amenities": [],
            "walk_minutes": walking_time,
            "drive_minutes": drive_minutes,
            "distance_miles": distance_miles,
            "day_pass_price": day_pass_price,
            "effective_price": effective_price,
            "pricing_status": pricing_status,
            "access_type": access_type,
            "is_open_now": False if "closed" in resolved_hours_summary.lower() else True,
            "opening_hours_summary": resolved_hours_summary,
            "validation_status": "passed" if clean_eligibility == "Fits Your Criteria" else "warning" if clean_eligibility == "Alternative" else "failed",
            "eligibility_status": clean_eligibility,
            "confidence": 1.0 if clean_eligibility == "Fits Your Criteria" else 0.7 if clean_eligibility == "Alternative" else 0.3,
            "explanation": rationale or "Meets constraint criteria.",
            "data_warnings": ["Unverified pricing"] if effective_price is None else [],
            
            # Backward Compatibility Fields
            "facility": facility,
            "rank": rank,
            "match_quality": clean_match_quality or "Excellent Match",
            "recommendation_reason": rationale or "Recommended by TravelWell AI.",
            "card_summary": card_summary,
            "badge_subtitle": "Highest overall score" if rank == 1 else "Highest rating" if rank == 2 else "Lowest paid guest pass"
        }
        
        recommendations.append(recommendation_entry)
        rank += 1
        
    unique_recs = []
    seen_place_ids = set()
    seen_names = set()
    for r in recommendations:
        pid = r.get("place_id") or r.get("id")
        norm_name = ((r.get("name") or "") + "||" + (r.get("address") or "")).lower().strip()
        if pid:
            if pid in seen_place_ids:
                continue
            seen_place_ids.add(pid)
        if norm_name in seen_names:
            continue
        seen_names.add(norm_name)
        unique_recs.append(r)
    return unique_recs[:3]


@app.post("/api/recommend")
async def recommend_workout(request: Request):
    import json
    import traceback
    from fastapi.responses import StreamingResponse, JSONResponse
    from google.genai import types
    from google.adk.agents.run_config import RunConfig, StreamingMode
    from app.app_utils import services
    
    try:
        body = await request.json()
        
        location = body.get("location", "Chicago")
        
        from app.services.google_maps import geocode_address
        resolved_loc = geocode_address(location)
        resolved_lat = resolved_loc.get("lat", 41.8817)
        resolved_lng = resolved_loc.get("lng", -87.6278)
        resolved_name = resolved_loc.get("formatted_address") or resolved_loc.get("display_name") or location
        time_window = body.get("timeWindow", "6:00 PM - 9:00 PM")
        budget_sel = body.get("budgetSelection", "20")
        has_ymca = body.get("hasYmca", False)
        showers_req = body.get("showersReq", False)
        parking_req = body.get("parkingReq", False)
        pool_pref = body.get("poolPref", False)
        treadmill_pref = body.get("treadmillPref", False)
        
        req_amenities = []
        if showers_req: req_amenities.append("showers")
        if parking_req: req_amenities.append("free parking")
        
        pref_amenities = []
        if pool_pref: pref_amenities.append("indoor pool")
        if treadmill_pref: pref_amenities.append("treadmill")
        
        membership_text = "I have a YMCA membership" if has_ymca else "I do not have any memberships"
        budget_text = "no budget limit" if budget_sel == "none" else f"a budget of $0 (free only)" if budget_sel == "free" else f"a budget of ${budget_sel}"
        
        prompt = f"I am at {location}. I need to find a gym with {' and '.join(req_amenities) if req_amenities else 'workout access'} between {time_window}. {membership_text}, and {budget_text}. My preferred amenities are {', '.join(pref_amenities) if pref_amenities else 'none'}."
        
        runner = request.app.state.runner
        user_id = f"user_{os.urandom(4).hex()}"
        session_id = f"session_{os.urandom(4).hex()}"
    except Exception as e:
        tb = traceback.format_exc()
        print(f"API initialization error: {e}\n{tb}")
        return JSONResponse(
            status_code=500,
            content={
                "type": "error",
                "error_type": type(e).__name__,
                "stage": "initialization",
                "message": str(e),
                "details": tb
            }
        )
    
    async def event_generator():
        message = types.Content(role="user", parts=[types.Part.from_text(text=prompt)])
        current_agent = "research_intelligence"
        full_markdown_text = ""
        try:
            events = runner.run(
                new_message=message,
                user_id=user_id,
                session_id=session_id,
                run_config=RunConfig(streaming_mode=StreamingMode.SSE)
            )
            for event in events:
                if getattr(event, "author", None):
                    current_agent = event.author
                event_dict = {
                    "author": getattr(event, "author", "unknown"),
                    "content": {
                        "role": event.content.role if getattr(event, "content", None) else "model",
                        "parts": [{"text": getattr(p, "text", "")} for p in event.content.parts] if getattr(event, "content", None) and getattr(event.content, "parts", None) else []
                    } if getattr(event, "content", None) else None
                }
                
                if event_dict["content"] and event_dict["content"]["parts"]:
                    for part in event_dict["content"]["parts"]:
                        if part.get("text"):
                            full_markdown_text += part["text"]
                            
                yield f"data: {json.dumps(event_dict)}\n\n"
                
            # Stream final structured output
            recommendations = parse_markdown_to_recommendations(full_markdown_text, budget_sel=budget_sel, has_ymca=has_ymca)
            
            data_warnings = []
            if not recommendations:
                data_warnings.append("No recommendations parsed from streaming response.")
                
            data_source = "fallback"
            if recommendations:
                data_source = "live" if os.getenv("GOOGLE_MAPS_API_KEY") else "mock"
                
            final_event = {
                "type": "result",
                "data": {
                    "resolvedLocation": {
                        "display_name": resolved_name,
                        "lat": resolved_lat,
                        "lng": resolved_lng
                    },
                    "recommendations": recommendations,
                    "selectedFacility": recommendations[0]["facility"] if recommendations else {},
                    "policyCheck": {
                        "status": "passed" if recommendations else "failed",
                        "satisfied_constraints": ["budget", "membership", "amenities"] if recommendations else [],
                        "violated_constraints": [] if recommendations else ["budget"]
                    },
                    "timeline": ["research_intelligence", "ranking_itinerary", "policy_validation"],
                    "dataSource": data_source,
                    "dataWarnings": data_warnings,
                    "summary": full_markdown_text
                }
            }
            yield f"data: {json.dumps(final_event)}\n\n"
            
        except Exception as e:
            tb = traceback.format_exc()
            print(f"Agent execution stream error during {current_agent}: {e}\n{tb}")
            
            err_msg = str(e)
            if "429" in err_msg or "RESOURCE_EXHAUSTED" in err_msg:
                err_msg = "Google Vertex AI Rate limit exceeded (429 Resource Exhausted). Please wait a moment and try again."
                
            err_dict = {
                "type": "error",
                "author": "system_error",
                "error_type": type(e).__name__,
                "stage": current_agent,
                "message": err_msg,
                "details": tb
            }
            yield f"data: {json.dumps(err_dict)}\n\n"
            
    return StreamingResponse(event_generator(), media_type="text/event-stream")


# Main execution
if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)
